//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomodoro.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Pomodoro {
            get {
                return ResourceManager.GetString("Pomodoro", resourceCulture);
            }
        }
        
        public static string Pomodoro_Completed {
            get {
                return ResourceManager.GetString("Pomodoro_Completed", resourceCulture);
            }
        }
        
        public static string Pomodoro_Focus {
            get {
                return ResourceManager.GetString("Pomodoro_Focus", resourceCulture);
            }
        }
        
        public static string Pomodoro_FocusMinutes {
            get {
                return ResourceManager.GetString("Pomodoro_FocusMinutes", resourceCulture);
            }
        }
        
        public static string Pomodoro_LongBreak {
            get {
                return ResourceManager.GetString("Pomodoro_LongBreak", resourceCulture);
            }
        }
        
        public static string Pomodoro_LongBreakMinutes {
            get {
                return ResourceManager.GetString("Pomodoro_LongBreakMinutes", resourceCulture);
            }
        }
        
        public static string Pomodoro_Pause {
            get {
                return ResourceManager.GetString("Pomodoro_Pause", resourceCulture);
            }
        }
        
        public static string Pomodoro_Reset {
            get {
                return ResourceManager.GetString("Pomodoro_Reset", resourceCulture);
            }
        }
        
        public static string Pomodoro_SessionsBeforeLongBreak {
            get {
                return ResourceManager.GetString("Pomodoro_SessionsBeforeLongBreak", resourceCulture);
            }
        }
        
        public static string Pomodoro_ShortBreak {
            get {
                return ResourceManager.GetString("Pomodoro_ShortBreak", resourceCulture);
            }
        }
        
        public static string Pomodoro_ShortBreakMinutes {
            get {
                return ResourceManager.GetString("Pomodoro_ShortBreakMinutes", resourceCulture);
            }
        }
        
        public static string Pomodoro_Skip {
            get {
                return ResourceManager.GetString("Pomodoro_Skip", resourceCulture);
            }
        }
        
        public static string Pomodoro_Start {
            get {
                return ResourceManager.GetString("Pomodoro_Start", resourceCulture);
            }
        }
        
        public static string Pomodoro_Subtitle {
            get {
                return ResourceManager.GetString("Pomodoro_Subtitle", resourceCulture);
            }
        }
        
        public static string Pomodoro_Title {
            get {
                return ResourceManager.GetString("Pomodoro_Title", resourceCulture);
            }
        }
    }
}
