//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notes.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get quick access to one of your notes.
        /// </summary>
        public static string Notes_Subtitle {
            get {
                return ResourceManager.GetString("Notes_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Notes_Title {
            get {
                return ResourceManager.GetString("Notes_Title", resourceCulture);
            }
        }
        
        public static string Notes_Clear {
            get {
                return ResourceManager.GetString("Notes_Clear", resourceCulture);
            }
        }
        
        public static string Notes_Duplicate {
            get {
                return ResourceManager.GetString("Notes_Duplicate", resourceCulture);
            }
        }
        
        public static string Notes_Setting_AccentColor {
            get {
                return ResourceManager.GetString("Notes_Setting_AccentColor", resourceCulture);
            }
        }
        
        public static string Notes_Setting_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Notes_Setting_AlwaysOnTop", resourceCulture);
            }
        }
        
        public static string Notes_Setting_BackgroundColor {
            get {
                return ResourceManager.GetString("Notes_Setting_BackgroundColor", resourceCulture);
            }
        }
        
        public static string Notes_Setting_Blur {
            get {
                return ResourceManager.GetString("Notes_Setting_Blur", resourceCulture);
            }
        }
        
        public static string Notes_Setting_ChecklistMode {
            get {
                return ResourceManager.GetString("Notes_Setting_ChecklistMode", resourceCulture);
            }
        }
        
        public static string Notes_Setting_Clear {
            get {
                return ResourceManager.GetString("Notes_Setting_Clear", resourceCulture);
            }
        }
        
        public static string Notes_Setting_Compact {
            get {
                return ResourceManager.GetString("Notes_Setting_Compact", resourceCulture);
            }
        }
        
        public static string Notes_Setting_DuplicateContent {
            get {
                return ResourceManager.GetString("Notes_Setting_DuplicateContent", resourceCulture);
            }
        }
        
        public static string Notes_Setting_DuplicateStyle {
            get {
                return ResourceManager.GetString("Notes_Setting_DuplicateStyle", resourceCulture);
            }
        }
        
        public static string Notes_Setting_Font {
            get {
                return ResourceManager.GetString("Notes_Setting_Font", resourceCulture);
            }
        }
        
        public static string Notes_Setting_FontSize {
            get {
                return ResourceManager.GetString("Notes_Setting_FontSize", resourceCulture);
            }
        }
        
        public static string Notes_Setting_HeaderColor {
            get {
                return ResourceManager.GetString("Notes_Setting_HeaderColor", resourceCulture);
            }
        }
        
        public static string Notes_Setting_LineSpacing {
            get {
                return ResourceManager.GetString("Notes_Setting_LineSpacing", resourceCulture);
            }
        }
        
        public static string Notes_Setting_LocalBackup {
            get {
                return ResourceManager.GetString("Notes_Setting_LocalBackup", resourceCulture);
            }
        }
        
        public static string Notes_Setting_LockEditing {
            get {
                return ResourceManager.GetString("Notes_Setting_LockEditing", resourceCulture);
            }
        }
        
        public static string Notes_Setting_MaxCharacters {
            get {
                return ResourceManager.GetString("Notes_Setting_MaxCharacters", resourceCulture);
            }
        }
        
        public static string Notes_Setting_MaxLines {
            get {
                return ResourceManager.GetString("Notes_Setting_MaxLines", resourceCulture);
            }
        }
        
        public static string Notes_Setting_Opacity {
            get {
                return ResourceManager.GetString("Notes_Setting_Opacity", resourceCulture);
            }
        }
        
        public static string Notes_Setting_Pinned {
            get {
                return ResourceManager.GetString("Notes_Setting_Pinned", resourceCulture);
            }
        }
        
        public static string Notes_Setting_Template {
            get {
                return ResourceManager.GetString("Notes_Setting_Template", resourceCulture);
            }
        }
        
        public static string Notes_Setting_TextAlignment {
            get {
                return ResourceManager.GetString("Notes_Setting_TextAlignment", resourceCulture);
            }
        }
        
        public static string Notes_Setting_TextColor {
            get {
                return ResourceManager.GetString("Notes_Setting_TextColor", resourceCulture);
            }
        }
        
        public static string Notes_Settings_Actions {
            get {
                return ResourceManager.GetString("Notes_Settings_Actions", resourceCulture);
            }
        }
        
        public static string Notes_Settings_Appearance {
            get {
                return ResourceManager.GetString("Notes_Settings_Appearance", resourceCulture);
            }
        }
        
        public static string Notes_Settings_Limits {
            get {
                return ResourceManager.GetString("Notes_Settings_Limits", resourceCulture);
            }
        }
        
        public static string Notes_Settings_Typography {
            get {
                return ResourceManager.GetString("Notes_Settings_Typography", resourceCulture);
            }
        }
        
        public static string Notes_Template_ClassNotes {
            get {
                return ResourceManager.GetString("Notes_Template_ClassNotes", resourceCulture);
            }
        }
        
        public static string Notes_Template_DailyPlan {
            get {
                return ResourceManager.GetString("Notes_Template_DailyPlan", resourceCulture);
            }
        }
        
        public static string Notes_Template_MeetingNotes {
            get {
                return ResourceManager.GetString("Notes_Template_MeetingNotes", resourceCulture);
            }
        }
        
        public static string Notes_Template_Scratchpad {
            get {
                return ResourceManager.GetString("Notes_Template_Scratchpad", resourceCulture);
            }
        }
        
        public static string Notes_Template_ToDoList {
            get {
                return ResourceManager.GetString("Notes_Template_ToDoList", resourceCulture);
            }
        }
    }
}
