//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotify.Locales
{
    using System;

    public class Locale
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Locale()
        {
        }

        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                    resourceMan = new global::System.Resources.ResourceManager("Spotify.Locales.Locale", typeof(Locale).Assembly);

                return resourceMan;
            }
        }

        public static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Spotify => ResourceManager.GetString("Spotify", resourceCulture) ?? "Spotify";

        public static string Spotify_Title => ResourceManager.GetString("Spotify_Title", resourceCulture) ?? "Spotify Player";

        public static string Spotify_Subtitle => ResourceManager.GetString("Spotify_Subtitle", resourceCulture) ?? "Playlists, artwork, progress, and playback controls";
    }
}
